[project]
name = "flaskstar"
version = "0.1.0"
description = "Flask front end for RAGstar project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "gunicorn>=23.0.0",
    "requests>=2.32.5",
]
