apiVersion: v1
kind: Service
metadata:
  name: flaskstar
  namespace: ragstar
  labels:
    app: flaskstar
  annotations:
    cloud.google.com/backend-config: '{"default": "flaskstar-backend"}'
spec:
  selector:
    app: flaskstar
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
