apiVersion: v1
kind: Service
metadata:
  name: flaskstar
  namespace: ragstar
  labels:
    app: flaskstar
spec:
  selector:
    app: flaskstar
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
